# Generated by Django 5.1.4 on 2025-02-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_company_name_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='taux_avance',
            field=models.IntegerField(default=0, help_text="Pourcentage d'avance requis pour les annonces"),
        ),
    ]
