# Generated by Django 5.1.4 on 2025-01-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'add_tarifs_horaires'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingInfo',
        ),
    ]
