# Generated by Django 5.1.4 on 2025-01-28 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_delete_billinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tarif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.tarif'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('table', 'Table')], max_length=20),
        ),
    ]
