# Generated by Django 5.1.4 on 2025-02-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_annonce_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'En attente'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=20),
        ),
    ]
