# Generated by Django 5.1.4 on 2025-02-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_annonce_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='annonce_categorie',
            field=models.CharField(default='Non spécifié', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='annonce_sous_categorie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='annonce_titre',
            field=models.CharField(default='Non spécifié', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='annonce_utilisateur_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='tarif_nom',
            field=models.CharField(default='Non spécifié', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='tarif_prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_email',
            field=models.EmailField(default='no-email@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_first_name',
            field=models.CharField(default='Non spécifié', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_last_name',
            field=models.CharField(default='Non spécifié', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
